function FooBar(
	a : TType;
	b : Integer;
	whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg : Boolean = True
) : String;
begin
	whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg := whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg or whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg;
end;

FooBar(whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg, whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg, whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg);

FooBar(
	whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg,
	whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg,
	whateverThisIsVeryLongggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
);